import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";

import preview from "../assets/preview.png";
import { getRandomPrompt } from "../utils";
import { FormField, Loader } from "../components";

function CreatePost() {
  const generateImg = async () => {
    if (form.prompt) {
      setGeneratingImg(true);

      try {
        const formattedPrompt = form.prompt
          .replace(/[.,\/#!$%\^&\*;:{}=\-_`~()]/g, "")
          .replaceAll(" ", "%20");

        const response = await axios.get(
          `https://widipe.com/dalle?text=${formattedPrompt}`,
          { responseType: "blob" }
        );

        const reader = new FileReader();
        reader.onloadend = () => {
          const base64data = reader.result;
          setForm({
            ...form,
            photo: base64data,
          });
        };
        reader.readAsDataURL(response.data);
      } catch (error) {
        console.error("Error generating image:", error);
        alert("An error occurred while generating the image.");
      } finally {
        setGeneratingImg(false);
      }
    } else {
      alert("Please enter a prompt");
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (form.prompt && form.photo) {
      setLoading(true);
      try {
        const response = await axios.post("http://localhost:8080/api/v1/post", {
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(form),
        });

        const data = await response.json();
        navigate("/");
      } catch (error) {
        alert(error);
      } finally {
        setLoading(false);
      }
    } else {
      alert("Please enter a prompt and generate an image");
    }
  };

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleSupriseMe = () => {
    const randomPrompt = getRandomPrompt(form.prompt);
    setForm({ ...form, prompt: randomPrompt });
  };

  const navigate = useNavigate();
  const [form, setForm] = useState({
    name: "",
    prompt: "",
    photo: "",
  });
  const [loading, setLoading] = useState(false);
  const [generatingImg, setGeneratingImg] = useState(false);

  return (
    <section className="mx-auto max-w-7xl">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">Dalle AI</h1>
        <p className="mt-2 text-[#666e75] text-[16px] max-w-[500px]">
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI
        </p>
      </div>

      <form onSubmit={handleSubmit} className="mt-10 max-w-3xl">
        <div className="flex flex-col gap-5">
          {/* <FormField
            labelName="Your name"
            type="text"
            name="name"
            placeholder="John Doe"
            value={form.name}
            handleChange={handleChange}
          /> */}
          <FormField
            labelName="Prompt"
            type="text"
            name="prompt"
            placeholder="A Samurai riding a Horse on Mars, lomography."
            value={form.prompt}
            handleChange={handleChange}
            isSupriseMe
            handleSupriseMe={handleSupriseMe}
          />

          <div className="relative bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg  focus:ring-blue-500 focus:border-blue-500 w-96 p-3 h-64 flex justify-center items-center mt-5">
            {form.photo ? (
              <img
                src={form.photo}
                alt="preview"
                className="w-full h-full object-contain"
              />
            ) : (
              <img
                src={preview}
                alt="preview"
                className="w-9/12 h-9/12 object-contain opacity-40"
              />
            )}

            {generatingImg && (
              <div className="absolute inset-0 z-0 flex justify-center items-center bg-[rgba(0,0,0,0.5)] rounded-lg">
                <Loader />
              </div>
            )}
          </div>
        </div>

        <div className="mt-10 flex gap-5">
          <button
            type="button"
            onClick={generateImg}
            className="text-white bg-green-700 w-full font-medium rounded-md text-sm  px-5 py-2.5 text-center sm:w-auto"
          >
            {generatingImg ? "Generating..." : "Generate"}
          </button>

          {form.photo && (
            <a
              href={form.photo}
              download="generated-image.png"
              className="text-white bg-blue-500 w-full font-medium rounded-md text-sm  px-5 py-2.5 text-center sm:w-auto"
            >
              Download Image
            </a>
          )}
        </div>

        {/* <div className="mt-10">
          <p className="mt-2 text-[#666e75] text-[14px]">
            Once you have created the image you want, you can share it with
            other in community
          </p>
          <button
            type="submit"
            className="mt-3 text-white bg-[#6469ff] font-medium rounded-md text-sm w-full px-5 py-2.5 text-center sm:w-auto"
          >
            {loading ? "Sharing..." : "Share with the community"}
          </button>
        </div> */}
      </form>
    </section>
  );
}

export default CreatePost;
